name: Build and Deploy to Hugging Face

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy-to-hf-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: run deploy.py
        run: python3 -m frontend.deploy

      - name: Push entire repository to Hugging Face Space
        run: |
          git clone --depth 1 https://Kiuyha:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Kiuyha/Surabaya-Opinion-Analytics hf-space
          if [ ! -d "hf-space" ]; then
            echo "Failed to clone Hugging Face space."
            exit 1
          fi
          cp -rT frontend/ hf-space/
          cd hf-space
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Build and deploy to Hugging Face Space" || echo "No changes to commit"
          git push