name: Monthly Retrain

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the training script
        run: python3 -m src.training.train_topics_model
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO_KMEANS_ID: ${{ secrets.HF_REPO_KMEANS_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      
      - name: Upload Plot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: visualizations
          path: visualizations
      
      - name: Upload Plot Artifact to Hugging Face Space
        run: |
          git clone --depth 1 https://Kiuyha:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Kiuyha/Surabaya-Opinion-Analytics hf-space
          if [ ! -d "hf-space" ]; then
            echo "Failed to clone Hugging Face space."
            exit 1
          fi
          mkdir -p hf-space/visualizations
          cp -rT visualizations/ hf-space/visualizations/
          cd hf-space
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f visualizations
          git commit -m "Add plot artifact from automated retraining" || echo "No changes to commit"
          git push
        